modkey = "Mod1"
mousekey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
layouts = ["MainAndVertStack", "MainAndHorizontalStack", "GridHorizontal", "Fibonacci"]
layout_mode = "Tag"
disable_current_tag_swap = false
focus_behaviour = "Sloppy"
focus_new_windows = true

[[scratchpad]]
name = "Kitty"
value = "alacritty"
x = 0.1
y = 0.1
height = 0.5
weidth = 0.5

[[keybind]]
command = "Execute"
value = "rofi -combi-modi window,run -show combi -modi combi"
modifier = ["Mod4"]
key = "r"

[[keybind]]
command = "Execute"
value = "rofi -show window"
modifier = ["modkey"]
key = "Tab"


[[keybind]]
command = "Execute"
value = "firefox-developer-edition"
modifier = ["Mod4"]
key = "f"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["Mod4"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "SoftReload"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "Execute"
value = "pkill leftwm"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "l"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "h"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "comma"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "comma"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "ToggleScratchPad"
value = "Kitty"
modifier = ["Mod4"]
key = "Tab"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "period"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "apostrophe"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"

